### ISSUE TITLE
Pin 96 has wrong name

### ISSUE THREAD

**Issue by ravenn37** [atctwo/pinout#1]
I spotted a mistake in [pins.js file](https://github.com/atctwo/pinout/blob/main/pins.js), as well as in the live version of the webpage. According to [Raspberry Pi CM4 Datasheet](https://datasheets.raspberrypi.com/cm4/cm4-datasheet.pdf), Pin 96 should be `AnalogIP0` instead of `AnalogIP1`. The description is correct, though.

**Comment by atctwo** [comment]
Hello!
I know it's been more than a year since this issue was opened, I unfortunately only saw this last night!  I never really monitored my GitHub notifications until recently, so I'm sorry I missed this!

I've fixed the error in commit 2610048ca0d8773eff694cf1e951ebac0cd310e9.    I've updated the live version on my website too.  Thank you for drawing it to my attention!
