### ISSUE TITLE
CM5?

### ISSUE THREAD

**Issue by V3lectronics** [atctwo/pinout#2]
You're pinout app was really useful for me in my project based around the CM4 (thank you!). I will probably switch to CM5 tho and was wandering if you are aware of the release of the CM5 and if you plan to update the tool to support the new CM5 pinout?
Thanks for the useful resource!

**Comment by atctwo** [comment]
Hello!  Sorry for taking so long to respond, my notifications weren't working!  

I'm really glad you found this useful!  I'm also pretty excited for the CM5 and I'm planning to get one as soon as they're available.  I probably will update this project when the CM5 comes out.  I actually had plans to make it work with pinouts for any device using JSON files for each device (that's why the repo name is so generic), but I never really got around to it.  Perhaps the CM5 is a good excuse to start working on it again!

**Comment by atctwo** [comment]
Hi again!  The pinout for the CM5 has been added.  When you go to the pinout tool you can pick between the CM4 and CM5.  I finally got around to dynamically loading device info from JSON files so hopefully I'll add other devices like the regular RPis at some point.  I had to change how the pin table looks because of the new way pins are added to the table, but I've also made some other stylistic improvements.

If you end up using it let me know if you run into any issues.  Finally, thank you for the motivation for me to finally implement the dynamic loading feature!

**Comment by V3lectronics** [comment]
Amazing thanks a lot! (Side note: it doesn't display too well on mobile but still usable)
